Name:           ros-indigo-dynpick-driver
Version:        0.0.6
Release:        0%{?dist}
Summary:        ROS dynpick_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/dynpick_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-roscpp
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-roscpp

%description
ROS driver package for Wacohtech dynpick force sensor

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Aug 11 2015 Isaac IY Saito <iiysaito@opensource-robotics.tokyo.jp> - 0.0.6-0
- Autogenerated by Bloom

* Wed Apr 01 2015 Isaac IY Saito <iiysaito@opensource-robotics.tokyo.jp> - 0.0.5-0
- Autogenerated by Bloom

* Mon Mar 23 2015 Isaac IY Saito <iiysaito@opensource-robotics.tokyo.jp> - 0.0.4-0
- Autogenerated by Bloom

* Mon Dec 29 2014 Isaac IY Saito <iiysaito@opensource-robotics.tokyo.jp> - 0.0.3-0
- Autogenerated by Bloom

* Wed Dec 24 2014 Isaac IY Saito <iiysaito@opensource-robotics.tokyo.jp> - 0.0.2-0
- Autogenerated by Bloom

